(function () {
  const columns = "ABCDEFGHIJKLM".split("");

  const TERRAIN = {
    sea: {
      name: "Sea",
      move: 99,
      defense: 0,
      impassable: true,
    },
    beach: {
      name: "Beach",
      move: 1,
      defense: 0,
    },
    open: {
      name: "Open",
      move: 1,
      defense: 0,
    },
    bocage: {
      name: "Bocage",
      move: 2,
      defense: 1,
    },
    town: {
      name: "Town",
      move: 1,
      defense: 2,
    },
    port: {
      name: "Port",
      move: 1,
      defense: 2,
    },
    highland: {
      name: "Highland",
      move: 2,
      defense: 1,
    },
    marsh: {
      name: "Marsh",
      move: 2,
      defense: 1,
    },
    river: {
      name: "River",
      move: 2,
      defense: 1,
    },
  };

  const rowTerrain = [
    "sea",
    "beach",
    "open",
    "bocage",
    "bocage",
    "bocage",
    "open",
    "bocage",
    "highland",
    "open",
  ];

  const terrainOverrides = {
    A2: "sea",
    M2: "sea",
    B3: "port",
    C4: "marsh",
    D4: "river",
    E4: "river",
    I4: "river",
    J5: "river",
    K5: "river",
    D5: "town",
    F5: "town",
    G6: "open",
    K6: "town",
    L6: "town",
    F8: "town",
    B8: "highland",
    M8: "open",
    A9: "open",
  };

  const labels = {
    C2: "Utah",
    E2: "Omaha",
    H2: "Gold",
    J2: "Juno",
    L2: "Sword",
    B3: "Cherbourg",
    D5: "Carentan",
    F5: "Bayeux",
    K6: "Caen",
    F8: "St-Lo",
    A9: "West Exit",
    M8: "East Exit",
  };

  const controlPoints = {
    C2: { name: "Utah Beach", kind: "beach", value: 1 },
    E2: { name: "Omaha Beach", kind: "beach", value: 1 },
    H2: { name: "Gold Beach", kind: "beach", value: 1 },
    J2: { name: "Juno Beach", kind: "beach", value: 1 },
    L2: { name: "Sword Beach", kind: "beach", value: 1 },
    B3: { name: "Cherbourg", kind: "port", value: 2 },
    D5: { name: "Carentan", kind: "town", value: 1 },
    F5: { name: "Bayeux", kind: "town", value: 1 },
    K6: { name: "Caen", kind: "town", value: 2 },
    F8: { name: "St-Lo", kind: "town", value: 2 },
    A9: { name: "Cotentin Exit", kind: "exit", value: 1 },
    M8: { name: "Vire Exit", kind: "exit", value: 1 },
  };

  const cells = [];
  const cellMap = {};
  for (let row = 1; row <= 10; row += 1) {
    for (let col = 0; col < columns.length; col += 1) {
      const id = `${columns[col]}${row}`;
      const terrain = terrainOverrides[id] || rowTerrain[row - 1];
      const cell = {
        id,
        col,
        row,
        terrain,
        label: labels[id] || "",
        objective: controlPoints[id] || null,
      };
      cells.push(cell);
      cellMap[id] = cell;
    }
  }

  const roads = [
    ["B3", "C3", "D4", "E4", "F5", "G5", "H5", "I5", "J5", "K6", "L6"],
    ["C2", "C3", "C4", "D5", "E5", "F5", "F6", "F7", "F8"],
    ["E2", "E3", "E4", "F5", "G6", "H6", "I6", "J6", "K6"],
    ["H2", "H3", "I4", "J5", "K6"],
    ["L2", "L3", "L4", "K5", "K6", "K7", "L8", "M8"],
  ];

  const roadEdges = new Set();
  for (const road of roads) {
    for (let i = 0; i < road.length - 1; i += 1) {
      roadEdges.add([road[i], road[i + 1]].sort().join("-"));
    }
  }

  const units = {
    us4inf: {
      id: "us4inf",
      side: "allied",
      name: "US 4th Infantry",
      short: "4 INF",
      type: "infantry",
      symbol: "XX",
      attack: 4,
      defense: 4,
      move: 3,
      steps: 2,
      traits: ["amphibious"],
    },
    us1inf: {
      id: "us1inf",
      side: "allied",
      name: "US 1st Infantry",
      short: "1 INF",
      type: "infantry",
      symbol: "XX",
      attack: 5,
      defense: 4,
      move: 3,
      steps: 2,
      traits: ["assault"],
    },
    us29inf: {
      id: "us29inf",
      side: "allied",
      name: "US 29th Infantry",
      short: "29 INF",
      type: "infantry",
      symbol: "XX",
      attack: 4,
      defense: 4,
      move: 3,
      steps: 2,
      traits: ["assault"],
    },
    us82ab: {
      id: "us82ab",
      side: "allied",
      name: "US 82nd Airborne",
      short: "82 AB",
      type: "airborne",
      symbol: "AB",
      attack: 3,
      defense: 3,
      move: 3,
      steps: 2,
      traits: ["airborne"],
    },
    us101ab: {
      id: "us101ab",
      side: "allied",
      name: "US 101st Airborne",
      short: "101 AB",
      type: "airborne",
      symbol: "AB",
      attack: 3,
      defense: 3,
      move: 3,
      steps: 2,
      traits: ["airborne"],
    },
    us2arm: {
      id: "us2arm",
      side: "allied",
      name: "US 2nd Armored",
      short: "2 ARM",
      type: "armor",
      symbol: "ARM",
      attack: 6,
      defense: 5,
      move: 5,
      steps: 2,
      traits: ["armor"],
    },
    usrangers: {
      id: "usrangers",
      side: "allied",
      name: "Ranger Group",
      short: "RGR",
      type: "commando",
      symbol: "RG",
      attack: 3,
      defense: 2,
      move: 3,
      steps: 1,
      traits: ["assault", "engineer"],
    },
    useng: {
      id: "useng",
      side: "allied",
      name: "Engineer Brigade",
      short: "ENG",
      type: "engineer",
      symbol: "ENG",
      attack: 2,
      defense: 3,
      move: 3,
      steps: 1,
      traits: ["engineer"],
    },
    uk50inf: {
      id: "uk50inf",
      side: "allied",
      name: "British 50th Infantry",
      short: "50 INF",
      type: "infantry",
      symbol: "XX",
      attack: 4,
      defense: 4,
      move: 3,
      steps: 2,
      traits: ["amphibious"],
    },
    uk3inf: {
      id: "uk3inf",
      side: "allied",
      name: "British 3rd Infantry",
      short: "3 INF",
      type: "infantry",
      symbol: "XX",
      attack: 4,
      defense: 4,
      move: 3,
      steps: 2,
      traits: ["amphibious"],
    },
    can3inf: {
      id: "can3inf",
      side: "allied",
      name: "Canadian 3rd Infantry",
      short: "3 CAN",
      type: "infantry",
      symbol: "XX",
      attack: 4,
      defense: 4,
      move: 3,
      steps: 2,
      traits: ["amphibious"],
    },
    uk6ab: {
      id: "uk6ab",
      side: "allied",
      name: "British 6th Airborne",
      short: "6 AB",
      type: "airborne",
      symbol: "AB",
      attack: 3,
      defense: 3,
      move: 3,
      steps: 2,
      traits: ["airborne"],
    },
    uk7arm: {
      id: "uk7arm",
      side: "allied",
      name: "British 7th Armoured",
      short: "7 ARM",
      type: "armor",
      symbol: "ARM",
      attack: 6,
      defense: 5,
      move: 5,
      steps: 2,
      traits: ["armor"],
    },
    alliedhq: {
      id: "alliedhq",
      side: "allied",
      name: "Allied Beach HQ",
      short: "HQ",
      type: "hq",
      symbol: "HQ",
      attack: 1,
      defense: 3,
      move: 2,
      steps: 1,
      traits: ["support"],
    },
    g709: {
      id: "g709",
      side: "german",
      name: "709th Static Division",
      short: "709",
      type: "infantry",
      symbol: "XX",
      attack: 3,
      defense: 4,
      move: 2,
      steps: 2,
      traits: ["static"],
    },
    g352: {
      id: "g352",
      side: "german",
      name: "352nd Infantry",
      short: "352",
      type: "infantry",
      symbol: "XX",
      attack: 5,
      defense: 4,
      move: 3,
      steps: 2,
      traits: ["veteran"],
    },
    g716: {
      id: "g716",
      side: "german",
      name: "716th Static Division",
      short: "716",
      type: "infantry",
      symbol: "XX",
      attack: 3,
      defense: 4,
      move: 2,
      steps: 2,
      traits: ["static"],
    },
    g736: {
      id: "g736",
      side: "german",
      name: "736th Regiment",
      short: "736",
      type: "infantry",
      symbol: "III",
      attack: 3,
      defense: 3,
      move: 2,
      steps: 1,
      traits: ["static"],
    },
    g243: {
      id: "g243",
      side: "german",
      name: "Cherbourg Garrison",
      short: "243",
      type: "garrison",
      symbol: "GAR",
      attack: 2,
      defense: 5,
      move: 1,
      steps: 2,
      traits: ["fortress"],
    },
    g914: {
      id: "g914",
      side: "german",
      name: "914th Regiment",
      short: "914",
      type: "infantry",
      symbol: "III",
      attack: 3,
      defense: 3,
      move: 3,
      steps: 1,
      traits: [],
    },
    g915: {
      id: "g915",
      side: "german",
      name: "915th Regiment",
      short: "915",
      type: "infantry",
      symbol: "III",
      attack: 3,
      defense: 3,
      move: 3,
      steps: 1,
      traits: [],
    },
    g21pz: {
      id: "g21pz",
      side: "german",
      name: "21st Panzer",
      short: "21 PZ",
      type: "armor",
      symbol: "PZ",
      attack: 6,
      defense: 5,
      move: 5,
      steps: 2,
      traits: ["armor"],
    },
    g12ss: {
      id: "g12ss",
      side: "german",
      name: "12th SS Panzer",
      short: "12 SS",
      type: "armor",
      symbol: "PZ",
      attack: 7,
      defense: 5,
      move: 5,
      steps: 2,
      traits: ["armor", "veteran"],
    },
    gpanzerlehr: {
      id: "gpanzerlehr",
      side: "german",
      name: "Panzer Lehr",
      short: "LEHR",
      type: "armor",
      symbol: "PZ",
      attack: 7,
      defense: 5,
      move: 5,
      steps: 2,
      traits: ["armor", "veteran"],
    },
    g77: {
      id: "g77",
      side: "german",
      name: "77th Infantry",
      short: "77",
      type: "infantry",
      symbol: "XX",
      attack: 4,
      defense: 4,
      move: 3,
      steps: 2,
      traits: [],
    },
  };

  const commonEvents = [
    {
      id: "naval-gunfire",
      title: "Naval Gunfire",
      text: "Allied attacks gain +2 this turn.",
      effect: { type: "modifier", side: "allied", key: "attack", value: 2 },
    },
    {
      id: "low-cloud",
      title: "Low Cloud",
      text: "Allied attacks suffer -1 this turn.",
      effect: { type: "modifier", side: "allied", key: "attack", value: -1 },
    },
    {
      id: "beach-congestion",
      title: "Beach Congestion",
      text: "Allied movement is -1 this turn.",
      effect: { type: "modifier", side: "allied", key: "move", value: -1 },
    },
    {
      id: "engineers-forward",
      title: "Engineers Forward",
      text: "Allied movement is +1 this turn.",
      effect: { type: "modifier", side: "allied", key: "move", value: 1 },
    },
    {
      id: "fuel-shortage",
      title: "Fuel Shortage",
      text: "German movement is -1 this turn.",
      effect: { type: "modifier", side: "german", key: "move", value: -1 },
    },
    {
      id: "local-counterattack",
      title: "Local Counterattack",
      text: "German attacks gain +1 this turn.",
      effect: { type: "modifier", side: "german", key: "attack", value: 1 },
    },
    {
      id: "reserve-release",
      title: "Reserve Release",
      text: "The next German reinforcement enters early.",
      effect: { type: "reinforce", side: "german" },
    },
    {
      id: "airborne-drop",
      title: "Airborne Disruption",
      text: "A random German unit loses one step.",
      effect: { type: "stepLoss", side: "german", amount: 1 },
    },
    {
      id: "coastal-batteries",
      title: "Coastal Batteries",
      text: "A random Allied unit loses one step.",
      effect: { type: "stepLoss", side: "allied", amount: 1 },
    },
    {
      id: "bocage-confusion",
      title: "Bocage Confusion",
      text: "Both sides attack at -1 this turn.",
      effect: { type: "dualModifier", key: "attack", value: -1 },
    },
    {
      id: "command-focus",
      title: "Command Focus",
      text: "Both sides defend at +1 this turn.",
      effect: { type: "dualModifier", key: "defense", value: 1 },
    },
    {
      id: "clear-weather",
      title: "Clear Weather",
      text: "Allied movement and attack gain +1 this turn.",
      effect: {
        type: "multiModifier",
        modifiers: [
          { side: "allied", key: "move", value: 1 },
          { side: "allied", key: "attack", value: 1 },
        ],
      },
    },
  ];

  const scenarios = [
    {
      id: "neptune",
      name: "Operation Neptune",
      turns: 12,
      summary: "Five landings, airborne lodgements, and the race for Caen and Cherbourg.",
      objectives: ["C2", "E2", "H2", "J2", "L2", "B3", "D5", "F5", "K6", "F8"],
      alliedWin: { points: 8, must: ["E2", "K6"] },
      deployments: [
        { ref: "us4inf", hex: "C2" },
        { ref: "us82ab", hex: "D4" },
        { ref: "us101ab", hex: "C4" },
        { ref: "us1inf", hex: "E2" },
        { ref: "us29inf", hex: "F2" },
        { ref: "usrangers", hex: "G2" },
        { ref: "uk50inf", hex: "H2" },
        { ref: "can3inf", hex: "J2" },
        { ref: "uk3inf", hex: "L2" },
        { ref: "uk6ab", hex: "L4" },
        { ref: "alliedhq", hex: "E3" },
        { ref: "us2arm", entry: "E2", reinforceTurn: 3 },
        { ref: "uk7arm", entry: "H2", reinforceTurn: 3 },
        { ref: "g243", hex: "B3" },
        { ref: "g709", hex: "C5" },
        { ref: "g352", hex: "F4" },
        { ref: "g716", hex: "H4" },
        { ref: "g736", hex: "L5" },
        { ref: "g21pz", hex: "K6" },
        { ref: "g914", hex: "D6" },
        { ref: "g915", hex: "F6" },
        { ref: "g77", hex: "A7" },
        { ref: "g12ss", entry: "K8", reinforceTurn: 4 },
        { ref: "gpanzerlehr", entry: "G9", reinforceTurn: 5 },
      ],
    },
    {
      id: "omaha",
      name: "Omaha Breakout",
      turns: 6,
      summary: "A tight west-center fight from the shingle through Bayeux and St-Lo.",
      objectives: ["E2", "F5", "F8", "D5"],
      alliedWin: { points: 4, must: ["F5"] },
      deployments: [
        { ref: "us1inf", hex: "E2" },
        { ref: "us29inf", hex: "F2" },
        { ref: "usrangers", hex: "G2" },
        { ref: "useng", hex: "E3" },
        { ref: "alliedhq", hex: "F3" },
        { ref: "us2arm", entry: "E2", reinforceTurn: 3 },
        { ref: "g352", hex: "F4" },
        { ref: "g716", hex: "H4" },
        { ref: "g914", hex: "D6" },
        { ref: "g915", hex: "F6" },
        { ref: "gpanzerlehr", entry: "F8", reinforceTurn: 4 },
      ],
    },
    {
      id: "caen",
      name: "Drive on Caen",
      turns: 8,
      summary: "British and Canadian forces push toward Caen against armored reserves.",
      objectives: ["H2", "J2", "L2", "K6", "M8"],
      alliedWin: { points: 5, must: ["K6"] },
      deployments: [
        { ref: "uk50inf", hex: "H2" },
        { ref: "can3inf", hex: "J2" },
        { ref: "uk3inf", hex: "L2" },
        { ref: "uk6ab", hex: "L4" },
        { ref: "alliedhq", hex: "J3" },
        { ref: "uk7arm", entry: "H2", reinforceTurn: 2 },
        { ref: "g716", hex: "H4" },
        { ref: "g736", hex: "L5" },
        { ref: "g21pz", hex: "K6" },
        { ref: "g12ss", entry: "K8", reinforceTurn: 3 },
        { ref: "gpanzerlehr", entry: "M8", reinforceTurn: 4 },
      ],
    },
  ];

  const normandyPrototypeData = {
    id: "normandy-prototype",
    name: "Normandy Prototype",
    description: "Original small Normandy operational prototype.",
    columns,
    rows: 10,
    TERRAIN,
    cells,
    cellMap,
    roads,
    roadEdges,
    controlPoints,
    units,
    scenarios,
    events: commonEvents,
  };

  window.DDAY_DATA = normandyPrototypeData;
  window.DDAY_DATASETS = window.DDAY_DATASETS || [];
  window.DDAY_DATASETS.push(normandyPrototypeData);
})();
